"use client";
import { FormEvent, useEffect, useState } from "react";
import { ArrowRight, Check, Clock3, MapPin } from "lucide-react";

type Service = { id: string; name: string; description: string | null; price: string; durationMinutes: number };
type Business = { name: string; slug: string; category: string | null; description: string | null; phone: string | null; email: string | null; services: Service[] };

function nextDays() {
    return Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() + index); return { key: date.toISOString().slice(0, 10), label: date.toLocaleDateString("en-ZA", { weekday: "short" }), day: date.getDate() }; });
}

export default function BookingPage({ params }: { params: Promise<{ businessSlug: string }> }) {
    const days = nextDays();
    const [businessSlug, setBusinessSlug] = useState(""); const [business, setBusiness] = useState<Business | null>(null); const [selected, setSelected] = useState(0); const [date, setDate] = useState(days[0].key); const [time, setTime] = useState(""); const [slots, setSlots] = useState<string[]>([]); const [done, setDone] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false);

    useEffect(() => { void params.then(({ businessSlug: slug }) => { setBusinessSlug(slug); void fetch(`/api/business/${encodeURIComponent(slug)}`).then(async (response) => { const result = await response.json(); if (!response.ok) setError(result.error || "Business not found."); else setBusiness(result.business); setLoading(false); }); }); }, [params]);
    useEffect(() => { const service = business?.services[selected]; if (!business || !service || !date) return; setTime(""); void fetch(`/api/availability?businessSlug=${encodeURIComponent(business.slug)}&service=${encodeURIComponent(service.name)}&date=${date}`).then(async (response) => { const result = await response.json(); setSlots(response.ok ? result.slots ?? [] : []); }).catch(() => setSlots([])); }, [business, date, selected]);

    async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!business) return; setSubmitting(true); setError(""); const data = new FormData(event.currentTarget); const response = await fetch("/api/bookings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ businessSlug, service: business.services[selected].name, date, time, name: data.get("name"), email: data.get("email"), phone: data.get("phone") }) }); const result = await response.json(); setSubmitting(false); if (!response.ok) { setError(result.error || "Unable to confirm your booking."); return; } setDone(true); }

    if (loading) return <main className="success"><div className="mono eyebrow">Smallbean booking page</div><h1>Loading business...</h1></main>;
    if (error || !business) return <main className="success"><div className="mono eyebrow">Smallbean booking page</div><h1>{error || "Business not found."}</h1><a className="button dark" href="/">Go to Smallbean <ArrowRight size={15} /></a></main>;
    const service = business.services[selected];
    return <main className="booking"><header className="topbar"><a className="brand" href="/">smallbean<span>·</span></a><span className="mono">Book with {business.name}</span></header><section className="booking-wrap">{done ? <div className="success"><div className="success-icon"><Check size={28} /></div><div className="mono eyebrow">You’re booked</div><h1>Your appointment is confirmed.</h1><p>{business.name} · {service.name} · {date} at {time}</p><a className="button dark" href="/">Powered by Smallbean <ArrowRight size={15} /></a></div> : <><div className="booking-intro"><div className="mono eyebrow">{business.category || "Service business"}</div><h1>{business.name}</h1><p>{business.description || "Book an appointment with this business through Smallbean."}</p>{business.email && <div className="location"><MapPin size={15} /> {business.email}</div>}</div><div className="booking-panel"><div className="mono">01 / Choose a service</div><div className="service-list">{business.services.map((item, index) => <button type="button" onClick={() => setSelected(index)} className={`service ${selected === index ? "chosen" : ""}`} key={item.id}><span><b>{item.name}</b><small>{item.description || "Appointment service"}</small></span><span><strong>R{Number(item.price).toLocaleString("en-ZA")}</strong><small><Clock3 size={13} /> {item.durationMinutes} min</small></span></button>)}</div><div className="mono">02 / Pick a day</div><div className="date-row">{days.map((item) => <button type="button" key={item.key} className={`date ${date === item.key ? "active-date" : ""}`} onClick={() => setDate(item.key)}><span>{item.day}</span>{item.label}</button>)}</div><div className="mono">03 / Pick a time</div>{slots.length === 0 ? <p className="form-error">No available times for this day.</p> : <div className="times">{slots.map((slot) => <button type="button" key={slot} className={time === slot ? "selected-time" : ""} onClick={() => setTime(slot)}>{slot}</button>)}</div>}<form onSubmit={submit}><div className="customer-fields"><input name="name" placeholder="Full name" required /><input name="email" type="email" placeholder="Email address" /><input name="phone" type="tel" placeholder="Phone number" required /></div>{error && <p className="form-error" role="alert">{error}</p>}<button className="button dark confirm" type="submit" disabled={submitting || !time}>{submitting ? "Confirming..." : "Confirm appointment"}<ArrowRight size={15} /></button></form></div></>}</section></main>;
}