"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Save } from "lucide-react";

export default function ProfilePage() {
    const [form, setForm] = useState({ name: "", slug: "", category: "", description: "", phone: "", email: "" }); const [message, setMessage] = useState(""); const [error, setError] = useState("");
    useEffect(() => { void fetch("/api/business/me").then(async (response) => { const result = await response.json(); if (response.ok) setForm(result.business); else setError(result.error); }); }, []);
    async function save(event: FormEvent) { event.preventDefault(); setError(""); setMessage(""); const response = await fetch("/api/business/me", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) setError(result.error); else { setForm(result.business); setMessage("Business profile saved."); } }
    return <main className="main"><div className="dash-head"><div><Link className="mono" href="/dashboard"><ArrowLeft size={13} /> Overview</Link><h1>Business profile</h1></div></div><form className="panel settings-form" onSubmit={save}><p className="form-help">This information appears on your public Smallbean booking page.</p><label>Business name<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><label>Booking link<input value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value.toLowerCase() })} required /><small>smallbean.co.za/{form.slug || "your-business"}</small></label><label>Category<input value={form.category || ""} onChange={(event) => setForm({ ...form, category: event.target.value })} placeholder="e.g. Beauty, tutoring, wellness" /></label><label>Description<textarea value={form.description || ""} onChange={(event) => setForm({ ...form, description: event.target.value })} rows={4} placeholder="Tell customers what your business offers" /></label><div className="form-row"><label>Phone<input value={form.phone || ""} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label><label>Email<input type="email" value={form.email || ""} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label></div>{error && <p className="form-error">{error}</p>}{message && <p className="form-success">{message}</p>}<button className="button dark" type="submit"><Save size={15} /> Save profile</button></form></main>;
}