import { PolicyPage } from "../../lib/policy-page";
import { pageMetadata } from "../../lib/seo";
export const metadata = pageMetadata({
    title: "Terms and conditions",
    description: "Review the terms for using Smallbean booking pages, business accounts, service listings, and subscription plans.",
    path: "/terms-and-conditions",
});
export default function TermsPage() {
    return <PolicyPage eyebrow="Legal" title="Terms & Conditions" intro="These Terms govern use of Smallbean Booking System, a platform for businesses to manage services, availability, customers and bookings." sections={[
        { title: "1. Accounts and the Smallbean service", paragraphs: ["By creating an account, accessing Smallbean, or using a booking page powered by Smallbean, you agree to these Terms. Anyone opening an account for a business confirms they are authorised to bind that business and its users.", "Smallbean provides software and booking tools. It is not the provider of a business's services and is not a party to the agreement between a business and its customer."] },
        { title: "2. Business responsibilities and bookings", paragraphs: ["Each business is solely responsible for the information, services, prices, availability, booking rules, cancellation terms, taxes, permits, customer communications and legal compliance that it publishes or applies. Businesses must keep their public booking information accurate, lawful and not misleading.", "Customers should direct service complaints, booking changes, deposits and booking-related refunds to the business that accepted the booking. Customer cancellation and rescheduling availability is determined by that business's settings."] },
        { title: "3. Plans, subscriptions and payments", paragraphs: ["Smallbean currently offers Free, Pro and Business plans. The available plan features, price, billing period and renewal information are displayed in the account before a paid plan is selected. Pro and Business plans are shown in ZAR and charged monthly unless the purchase flow states otherwise.", "Paid subscriptions are processed by the payment provider used in the checkout flow. Smallbean does not store full payment-card details. Businesses must keep billing details accurate and maintain authority to use the selected payment method. Failed payments may result in restricted access, suspension or cancellation in accordance with the payment provider's processes and applicable law."] },
        { title: "4. Acceptable use, availability and intellectual property", paragraphs: ["You may use Smallbean only for lawful business and booking purposes. You must not submit false or unlawful content, misuse customer information, send unsolicited communications, attempt unauthorised access, interfere with the service, or use the platform for fraud or malware.", "Smallbean aims to provide a reliable service but may be affected by maintenance, technical issues, third-party services or events outside reasonable control. We may update or discontinue features where reasonably necessary. Smallbean and its software, branding and content remain protected by intellectual-property law; you retain ownership of your business content and grant us the limited rights needed to operate the platform."] },
        { title: "5. Suspension, liability and changes", paragraphs: ["We may suspend or terminate access for material breach, non-payment, security or legal risk, or misuse. You may stop using the service at any time, subject to any active subscription arrangements.", "To the extent permitted by South African law, Smallbean is not liable for indirect, consequential or loss-of-profit damages, or disputes between a business and its customers. Nothing excludes rights that cannot lawfully be excluded. These Terms are governed by the laws of South Africa. We may update them by publishing a revised version with a new Last Updated date."] },
    ]} />;
}
