import { PolicyPage } from "../../lib/policy-page";
import { pageMetadata } from "../../lib/seo";
export const metadata = pageMetadata({
    title: "Privacy policy",
    description: "Read how Smallbean handles account, business, customer, and booking information under applicable South African privacy law.",
    path: "/privacy-policy",
});
export default function PrivacyPage() {
    return <PolicyPage eyebrow="Privacy" title="Privacy Policy" intro="This policy explains how Smallbean Booking System processes personal information in accordance with applicable South African data-protection law, including POPIA." sections={[
        { title: "1. Our role and the information we process", paragraphs: ["For account and platform-administration information, Smallbean generally determines why and how information is processed. For customer and booking information entered by a business, the business generally determines the purpose of processing and is responsible for its privacy notice; Smallbean processes that information as its operator/service provider.", "Information may include account details such as name, email, password hash and account activity; business details such as business name, contact information, services, prices and availability; and customer and booking details such as customer name, email, phone number, selected service, appointment and booking status."] },
        { title: "2. Why we use information", paragraphs: ["We use personal information to create and administer accounts, operate booking pages, create and manage appointments, provide notifications and support, maintain security, prevent misuse, improve the service and meet legal obligations. We do not sell personal information.", "We may process technical information such as device, browser, IP address, logs and timestamps to secure and operate the platform. Necessary session cookies are used to keep authenticated users signed in; any future optional analytics or similar technology will be accompanied by an appropriate notice or consent mechanism where required."] },
        { title: "3. Payments and service providers", paragraphs: ["Payment-card details for paid subscriptions are submitted directly to the payment provider used in the checkout flow and are handled under that provider's terms and privacy notice. Smallbean does not store full card details. We may receive limited payment information, such as a payment or subscription reference, status, amount, currency and billing period, to administer subscriptions and address payment queries.", "We may use providers for hosting, database infrastructure, security, communications and payments. They may process information only as needed to provide their services and subject to appropriate safeguards. Where information is processed outside South Africa, we will take steps required by POPIA to ensure a lawful transfer basis."] },
        { title: "4. Retention, security and your rights", paragraphs: ["We retain information while an account is active and thereafter only as reasonably necessary for security, dispute resolution, record-keeping and legal obligations. We use reasonable technical and organisational safeguards, but no internet service can be completely secure.", "Subject to POPIA, you may request access to, correction of or deletion of your information, object to certain processing, or ask how information is used. Requests relating to a business's customer booking information should normally be sent to that business. You may also lodge a complaint with the Information Regulator (South Africa)."] },
        { title: "5. Updates", paragraphs: ["We may update this policy when the service, our processing activities or legal requirements change. The current version will be published here with its Effective Date and Last Updated date."] },
    ]} />;
}
