"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CalendarOff, Trash2 } from "lucide-react";

type TimeOff = { id: string; startsAt: string; endsAt: string; reason?: string | null; staff?: { name: string } | null };
export default function TimeOffPage() {
    const [items, setItems] = useState<TimeOff[]>([]); const [form, setForm] = useState({ startsAt: "", endsAt: "", reason: "" }); const [error, setError] = useState("");
    useEffect(() => { void fetch("/api/time-off").then(async (response) => { const result = await response.json(); if (response.ok) setItems(result.timeOff); else setError(result.error); }); }, []);
    async function add(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/time-off", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) { setError(result.error); return; } setItems((current) => [...current, result.timeOff]); setForm({ startsAt: "", endsAt: "", reason: "" }); }
    async function remove(id: string) { const response = await fetch(`/api/time-off?id=${id}`, { method: "DELETE" }); if (response.ok) setItems((current) => current.filter((item) => item.id !== id)); }
    return <main className="main"><div className="dash-head"><div><Link className="mono" href="/dashboard"><ArrowLeft size={13} /> Overview</Link><h1>Time off</h1></div></div><section className="content-grid"><form className="panel service-form" onSubmit={add}><div className="panel-head"><h2>Block availability</h2><CalendarOff size={17} /></div><label>Starts<input type="datetime-local" value={form.startsAt} onChange={(event) => setForm({ ...form, startsAt: event.target.value })} required /></label><label>Ends<input type="datetime-local" value={form.endsAt} onChange={(event) => setForm({ ...form, endsAt: event.target.value })} required /></label><input placeholder="Reason (holiday, leave...)" value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} />{error && <p className="form-error">{error}</p>}<button className="button dark" type="submit">Block time <CalendarOff size={15} /></button></form><section className="panel"><div className="panel-head"><h2>Blocked periods</h2><span className="mono">{items.length} records</span></div>{items.length === 0 ? <p style={{ color: "var(--muted)" }}>No blocked dates.</p> : items.map((item) => <div className="appointment" key={item.id}><div className="avatar"><CalendarOff size={14} /></div><div><b>{new Date(item.startsAt).toLocaleString("en-ZA")}</b><small>until {new Date(item.endsAt).toLocaleString("en-ZA")} · {item.reason || "Unavailable"}</small></div><button className="icon-button" title="Remove blocked period" aria-label="Remove blocked period" onClick={() => void remove(item.id)}><Trash2 size={15} /></button></div>)}</section></section></main>;
}