"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Clock3, Plus, Trash2 } from "lucide-react";

type Service = { id: string; name: string; description?: string | null; price: number | string; durationMinutes: number; active: boolean };

export default function ServicesPage() {
    const [services, setServices] = useState<Service[]>([]); const [error, setError] = useState(""); const [form, setForm] = useState({ name: "", description: "", price: "", durationMinutes: "30" });
    useEffect(() => { void fetch("/api/services").then(async (response) => { const result = await response.json(); if (response.ok) setServices(result.services); else setError(result.error); }); }, []);
    async function addService(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const response = await fetch("/api/services", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, price: Number(form.price), durationMinutes: Number(form.durationMinutes) }) }); const result = await response.json(); if (!response.ok) { setError(result.error); return; } setServices((current) => [...current, result.service]); setForm({ name: "", description: "", price: "", durationMinutes: "30" }); }
    async function removeService(id: string) { const response = await fetch(`/api/services?id=${encodeURIComponent(id)}`, { method: "DELETE" }); if (!response.ok) { setError((await response.json()).error); return; } setServices((current) => current.filter((service) => service.id !== id)); }
    return <main className="main"><div className="dash-head"><div><Link className="mono" href="/dashboard"><ArrowLeft size={13} /> Overview</Link><h1>Services</h1></div></div><section className="content-grid"><form className="panel service-form" onSubmit={addService}><div className="panel-head"><h2>Add a service</h2><Plus size={17} /></div><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Service name" required /><textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Description (optional)" rows={3} /><div className="form-row"><input type="number" min="0" step="0.01" value={form.price} onChange={(event) => setForm({ ...form, price: event.target.value })} placeholder="Price in R" required /><input type="number" min="5" value={form.durationMinutes} onChange={(event) => setForm({ ...form, durationMinutes: event.target.value })} placeholder="Minutes" required /></div>{error && <p className="form-error">{error}</p>}<button className="button dark" type="submit">Add service <Plus size={15} /></button></form><section className="panel"><div className="panel-head"><h2>Your services</h2><span className="mono">{services.length} active records</span></div>{services.length === 0 ? <p style={{ color: "var(--muted)" }}>Add your first service to start accepting bookings.</p> : services.map((service) => <div className="appointment" key={service.id}><div className="avatar"><Clock3 size={14} /></div><div><b>{service.name}</b><small>{service.description || "Service offered through Smallbean."}</small></div><strong>R{Number(service.price).toLocaleString("en-ZA")} · {service.durationMinutes} min</strong><button className="icon-button" title={`Delete ${service.name}`} aria-label={`Delete ${service.name}`} onClick={() => void removeService(service.id)}><Trash2 size={15} /></button></div>)}</section></section></main>;
}