import Link from "next/link";
import { ArrowRight, CalendarCheck2, CalendarDays, ChartNoAxesColumn, Check, Clock3, Link2, ShieldCheck, Users } from "lucide-react";
import { MarketingFooter, MarketingHeader } from "../marketing-chrome";
import { pageMetadata } from "../../lib/seo";

export const metadata = pageMetadata({
    title: "Appointment booking features",
    description: "Explore Smallbean features for service businesses: online booking pages, service menus, availability, staff schedules, customer records, and booking rules.",
    path: "/features",
});
const features = [
    { icon: Link2, number: "01", label: "YOUR FRONT DOOR", title: "One page that does the explaining.", body: "Give every service its own name, description, duration, and price. Your public booking page brings the details together so customers can choose with confidence.", points: ["A shareable page for your business", "Services, prices, and durations", "Business details customers can find"] },
    { icon: Clock3, number: "02", label: "YOUR REAL HOURS", title: "Offer times you can actually keep.", body: "Set working hours, add time off, and account for service length. Customers see available slots that fit the schedule you have set.", points: ["Business and staff availability", "Time off and booking windows", "Conflict-aware appointment slots"] },
    { icon: Users, number: "03", label: "YOUR PEOPLE", title: "Know who’s coming through the door.", body: "Keep customer contact details and appointment history alongside the services and team that make your business work.", points: ["Customer records in one workspace", "Staff and service assignments", "Appointment notes and status"] },
    { icon: ShieldCheck, number: "04", label: "YOUR BOUNDARIES", title: "Make the booking rules yours.", body: "Decide how far ahead a customer can book, how much notice you need, and whether customers can cancel or reschedule themselves.", points: ["Minimum notice and advance windows", "Cancellation and rescheduling settings", "Secure appointment management links"] },
];

export default function FeaturesPage() {
    return <><MarketingHeader active="/features" /><main className="market-page">
        <section className="market-page-hero"><div className="market-page-hero-copy"><p className="market-eyebrow market-eyebrow-dark">A better booking rhythm</p><h1>Less admin.<br /><em>More of your craft.</em></h1><p>Smallbean gives your customers a clear next step and gives you a calmer way to run the day.</p><Link className="market-button market-button-dark" href="/auth">Create your booking page <ArrowRight size={16} /></Link></div><div className="market-page-stat"><span className="market-small-label">THE GOOD PART</span><strong>One link.<br />Your whole<br />booking flow.</strong><span className="market-page-stat-mark"><CalendarCheck2 size={22} /></span></div></section>
        <section className="market-feature-list">{features.map(({ icon: Icon, number, label, title, body, points }) => <article className="market-feature-row" key={number}><div className="market-feature-row-label"><span>{number}</span><Icon size={18} /><small>{label}</small></div><div className="market-feature-row-copy"><h2>{title}</h2><p>{body}</p><ul>{points.map((point) => <li key={point}><Check size={14} />{point}</li>)}</ul></div><div className={`market-feature-visual market-feature-visual-${number}`} aria-hidden="true"><div className="market-feature-visual-top"><span className="market-small-label">SMALLBEAN WORKSPACE</span><span className="market-feature-visual-dot" /></div>{number === "01" ? <div className="market-visual-link"><Link2 size={15} /><span>smallbean.co.za/studio-moya</span><Check size={14} /></div> : number === "02" ? <div className="market-visual-calendar"><span>MON <b>28</b></span><span className="active">TUE <b>29</b></span><span>WED <b>30</b></span><span>THU <b>01</b></span></div> : number === "03" ? <div className="market-visual-customer"><span className="market-visual-avatar">AM</span><span><strong>Amara Ndlovu</strong><small>4 appointments · Last seen 16 Sep</small></span><ArrowRight size={15} /></div> : <div className="market-visual-rule-list"><span><Check size={13} /> Book up to <b>60 days ahead</b></span><span><Check size={13} /> Require <b>2 hours’ notice</b></span><span><Check size={13} /> Customer rescheduling <b>On</b></span></div>}</div></article>)}</section>
        <section className="market-feature-plan"><div><p className="market-eyebrow">Room to grow</p><h2>Start with the essentials.<br /><em>Add more when it matters.</em></h2></div><div><p>Booking pages and availability are at the heart of every plan. Pro adds analytics and calendar tools; Business adds team capabilities.</p><Link className="market-button market-button-lime" href="/pricing">Compare plans <ArrowRight size={15} /></Link></div></section>
        <section className="market-feature-bottom"><div><CalendarDays size={18} /><span><strong>Appointments, not spreadsheets</strong><small>See bookings and customer details from your business workspace.</small></span></div><div><ChartNoAxesColumn size={18} /><span><strong>Useful insight, when you’re ready</strong><small>Analytics start with Pro, when your business is ready to look closer.</small></span></div></section>
    </main><MarketingFooter /></>;
}