import Link from "next/link";
import { ArrowUpRight, CalendarDays, ChartNoAxesColumn, Clock3, Copy, LayoutDashboard, Scissors, Settings, Share2, Users } from "lucide-react";
import { getCurrentTenant } from "../../lib/tenant";
import LinkActions from "./link-actions";

const links = [["Overview", LayoutDashboard, "/dashboard"], ["Calendar", CalendarDays, "/dashboard/appointments"], ["Bookings", Clock3, "/dashboard/appointments"], ["Customers", Users, "/dashboard/customers"], ["Services", Scissors, "/dashboard/services"], ["Staff", Users, "/dashboard/staff"], ["Availability", Clock3, "/dashboard/availability"], ["Time off", CalendarDays, "/dashboard/time-off"], ["Business profile", Settings, "/dashboard/profile"], ["Analytics", ChartNoAxesColumn, "/dashboard/analytics"]] as const;

export default async function Dashboard() {
    const tenant = await getCurrentTenant();
    let businessName = "Your business"; let slug = "your-business"; let appointments: { id: string; startsAt: Date; status: string; customer: { name: string }; service: { name: string } }[] = [];
    if (tenant && process.env.DATABASE_URL) { const { prisma } = await import("../../lib/database"); const organization = await prisma.organization.findUnique({ where: { id: tenant.organizationId }, select: { name: true, slug: true, appointments: { where: { status: { in: ["PENDING", "CONFIRMED", "RESCHEDULED"] } }, include: { customer: { select: { name: true } }, service: { select: { name: true } } }, orderBy: { startsAt: "asc" }, take: 5 } } }); if (organization) { businessName = organization.name; slug = organization.slug; appointments = organization.appointments; } }
    const firstName = tenant?.user.name.split(" ")[0] || "there";
    return <div className="dashboard"><aside className="sidebar"><Link href="/" className="brand">smallbean<span>·</span></Link>{links.map(([label, Icon, href], index) => <Link className={`side-link ${index === 0 ? "active" : ""}`} href={href} key={label}><Icon size={16} /><span>{label}</span></Link>)}</aside><main className="main"><div className="dash-head"><div><div className="mono eyebrow">Business workspace</div><h1>Good morning, {firstName}.</h1></div><Link className="button dark" href={`/book/${slug}`}>Preview booking page <ArrowUpRight size={15} /></Link></div><div className="stats"><div className="stat"><span className="mono">Upcoming bookings</span><strong>{appointments.length}</strong><small>Across your workspace</small></div><div className="stat"><span className="mono">Business link</span><strong>1</strong><small>Ready to share</small></div><div className="stat"><span className="mono">Services</span><strong>Live</strong><small>Manage your offering</small></div><div className="stat"><span className="mono">Customers</span><strong>CRM</strong><small>Every relationship in one place</small></div></div><section className="link-panel"><div><p className="mono eyebrow">Your Smallbean booking link</p><h2>smallbean.co.za/{slug}</h2><p>Share this link in your Instagram, TikTok, Facebook, and WhatsApp profiles.</p></div><LinkActions slug={slug} /></section><div className="content-grid"><section className="panel"><div className="panel-head"><h2>Upcoming bookings</h2><Link className="mono" href="/dashboard/appointments">View all <ArrowUpRight size={13} /></Link></div>{appointments.length === 0 ? <p style={{ color: "var(--muted)" }}>Your confirmed bookings will appear here.</p> : appointments.map((item) => <div className="appointment" key={item.id}><time>{item.startsAt.toLocaleString("en-ZA", { dateStyle: "medium", timeStyle: "short" })}</time><div className="avatar">{item.customer.name.slice(0, 2).toUpperCase()}</div><div><b>{item.customer.name}</b><small>{item.service.name}</small></div><span className="status">{item.status}</span></div>)}</section><aside className="panel"><div className="panel-head"><h2>Get ready</h2><span className="mono">Smallbean</span></div><p style={{ color: "var(--muted)", fontSize: 13, lineHeight: 1.6 }}>Complete your profile, add services, and set your hours before sharing your booking link.</p><ul className="checklist"><li>Business profile</li><li>Services and prices</li><li>Opening hours</li><li>Share your link</li></ul></aside></div></main></div>;
}