"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CalendarDays, Clock3 } from "lucide-react";
import Link from "next/link";

type Appointment = { id: string; startsAt: string; endsAt: string; status: string; customer?: { name: string; email?: string }; service?: { name: string }; staff?: { name: string } | null };
const weekDays = Array.from({ length: 7 }, (_, index) => { const day = new Date(); day.setHours(0, 0, 0, 0); day.setDate(day.getDate() + index); return day; });

export default function AppointmentsPage() {
    const [items, setItems] = useState<Appointment[]>([]); const [error, setError] = useState("");
    useEffect(() => { void fetch("/api/appointments").then(async (response) => { const result = await response.json(); if (!response.ok) setError(result.error); else setItems(result.appointments); }); }, []);
    async function update(id: string, status: string) { const response = await fetch("/api/appointments", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status }) }); if (!response.ok) { setError((await response.json()).error); return; } setItems((current) => current.map((item) => item.id === id ? { ...item, status } : item)); }
    const grouped = useMemo(() => weekDays.map((day) => ({ day, items: items.filter((item) => new Date(item.startsAt).toDateString() === day.toDateString()) })), [items]);
    return <main className="main"><div className="dash-head"><div><Link className="mono" href="/dashboard"><ArrowLeft size={13} /> Overview</Link><h1>Calendar</h1></div><span className="mono">Next 7 days</span></div>{error && <p className="form-error">{error}</p>}<section className="calendar-grid">{grouped.map(({ day, items: dayItems }) => <div className="calendar-day" key={day.toISOString()}><div className="calendar-day-head"><span className="mono">{day.toLocaleDateString("en-ZA", { weekday: "short" })}</span><strong>{day.getDate()}</strong></div>{dayItems.length === 0 ? <p className="calendar-empty">Open</p> : dayItems.map((item) => <article className="calendar-event" key={item.id}><time><Clock3 size={12} /> {new Date(item.startsAt).toLocaleTimeString("en-ZA", { hour: "2-digit", minute: "2-digit" })}</time><b>{item.customer?.name}</b><small>{item.service?.name}</small><select aria-label={`Status for ${item.customer?.name}`} value={item.status} onChange={(event) => void update(item.id, event.target.value)}><option>CONFIRMED</option><option>COMPLETED</option><option>NO_SHOW</option><option>CANCELLED</option></select></article>)}</div>)}</section><section className="panel calendar-list"><div className="panel-head"><h2>All appointments</h2><span className="mono">{items.length} records</span></div>{items.length === 0 && !error && <p style={{ color: "var(--muted)" }}>No appointments yet.</p>}{items.map((item) => <div className="appointment" key={item.id}><time><CalendarDays size={13} /> {new Date(item.startsAt).toLocaleString("en-ZA")}</time><div className="avatar">{item.customer?.name?.slice(0, 2).toUpperCase()}</div><div><b>{item.customer?.name}</b><small>{item.service?.name} {item.staff ? `· ${item.staff.name}` : ""}</small></div><span className="status">{item.status}</span></div>)}</section></main>;
}
